export let uni = [
	{
		id: 1,
		uni_nome: 'UNIR',
		uni_link: 'https://www.unir.br/homepage',
		cursos: {
			c1: 'Português',
			cl1: 'https://letrasguajara.unir.br/homepage',
			e1: 'ppc',
			el1: 'https://letrasguajara.unir.br/uploads/47327670/arquivos/ppc_letras_portugues_guajara_1064761354.pdf',
			c2: 'Português',
			cl2: 'https://dlv.unir.br/pagina/exibir/11758',
			e2: 'ementa',
			el2: 'https://dlv.unir.br/uploads/30303030/Grade%20e%20ementas%20do%20PPC%202018/5%20LINGUA%20LATINA.pdf',
			c3: 'Português',
			cl3: 'https://dell.unir.br/homepage',
			e3: 'latim 1',
			el3: 'https://dell.unir.br/uploads/91190067/Atas%20Reunioes%202021/EMENTAS%20CURSO%20LETRAS/L%C3%8DNGUA%20LATINA%20I.pdf',
			c4: 'Espanhol',
			cl4: 'https://letrasespanhol.unir.br/homepage',
			e4: 'ppc',
			el4: 'https://letrasespanhol.unir.br/uploads/61965746/PPC%20Espanhol%202017.pdf',
			c5: 'Inglês',
			cl5: 'https://letrasingles.unir.br/homepage',
			e5: 'matriz curricular',
			el5: 'https://letrasingles.unir.br/uploads/98051164/TCC%202017%20A%202020/quarto%20periodo.pdf',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 2,
		uni_nome: 'UFRR',
		uni_link: 'https://ufrr.br/',
		cursos: {
			c1: 'Português',
			cl1: 'https://ufrr.br/letrasportugues/',
			e1: 'ppc',
			el1: 'https://ufrr.br/letrasportugues/wp-content/uploads/sites/30/2023/07/PPC-Letras-Portugues-2018.pdf',
			c2: 'Português e Francês',
			cl2: 'https://ufrr.br/letrasfrances/',
			e2: 'ppc',
			el2: 'https://ufrr.br/letrasfrances/wp-content/uploads/sites/32/2023/07/PPC-Letras-Frances_2018.pdf',
			c3: 'Português e Espanhol',
			cl3: 'https://ufrr.br/letrasespanhol/',
			e3: 'ppc',
			el3: 'https://ufrr-my.sharepoint.com/personal/tatiana_capaverde_ufrr_br/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Ftatiana%5Fcapaverde%5Fufrr%5Fbr%2FDocuments%2FAnexos%2FPPC%5FLetras%5FEspanhol%5F2018%20final%20com%20errata%2021%20%282%29%2Epdf&parent=%2Fpersonal%2Ftatiana%5Fcapaverde%5Fufrr%5Fbr%2FDocuments%2FAnexos&ga=1',
			c4: 'Português e Inglês',
			cl4: 'https://ufrr.br/letrasingles/',
			e4: 'ppc',
			el4: 'https://drive.google.com/file/d/1d4hH9xIoseJfaFx72PSYUubWUKsnc0Yz/view',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 3,
		uni_nome: 'UFAC',
		uni_link: 'https://www.ufac.br/site',
		cursos: {
			c1: 'Espanhol',
			cl1: 'http://www2.ufac.br/cel/espanhol',
			e1: 'ppc',
			el1: 'http://www2.ufac.br/cel/espanhol/projeto-pedagogico-do-curso.pdf/',
			c2: 'Inglês',
			cl2: 'http://www2.ufac.br/cel/ingles',
			e2: 'ppc',
			el2: 'http://www2.ufac.br/cel/ingles/ppc2019.pdf/',
			c3: 'Português',
			cl3: 'http://www2.ufac.br/cela/espanhol',
			e3: 'ppc',
			el3: 'http://www2.ufac.br/cel/portugues/documentos/projetos-pedagogicos/ppc-2019.pdf/view',
			c4: 'Espanhol',
			cl4: 'http://www2.ufac.br/cela/espanhol',
			e4: 'ppc',
			el4: 'http://www2.ufac.br/cela/espanhol/ppc2007.pdf/',
			c5: 'Francês',
			cl5: 'http://www2.ufac.br/cela/frances',
			e5: 'ppc',
			el5: 'http://www2.ufac.br/cela/frances/projeto-pedagogico-do-curso.pdf',
			c6: 'Inglês',
			cl6: 'http://www2.ufac.br/cela/ingles',
			e6: 'ppc',
			el6: 'http://www2.ufac.br/cela/ingles/projeto-pedagogico-curricular/ppc.pdf',
			c7: 'Português',
			cl7: 'http://www2.ufac.br/cela/portugues',
			e7: 'ppc',
			el7: 'http://www2.ufac.br/cela/portugues/projeto-pedagogico-do-curso-ppc.pdf/view'
		}
	},
	{
		id: 4,
		uni_nome: 'UNIFAP',
		uni_link: 'http://www.unifap.br/',
		cursos: {
			c1: 'Português-Inglês',
			cl1: 'https://www2.unifap.br/letras/',
			e1: 'ppc',
			el1: 'https://www2.unifap.br/letras/files/2013/12/Projeto-Pedag%c3%b3gico-do-Curso-de-Letras-Portugu%c3%aas-IngL%c3%aas1.docx',
			c2: 'Português-Francês',
			cl2: 'https://www2.unifap.br/letras/',
			e2: 'ppc',
			el2: 'https://www2.unifap.br/letras/files/2022/07/PPC-2019.pdf',
			c3: 'Português-Francês',
			cl3: 'https://www2.unifap.br/letras/',
			e3: 'ppc',
			el3: 'https://www2.unifap.br/letras/files/2013/12/Projeto-Pedag%c3%b3gico-do-Curso-de-Letras-Portugu%c3%aas-Franc%c3%aas-PARFOR.pdf',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 5,
		uni_nome: 'UFAM',
		uni_link: 'https://www.ufam.edu.br/',
		cursos: {
			c1: 'Espanhol',
			cl1: 'https://letrasespanhol.ufam.edu.br/',
			e1: 'ppc',
			el1: 'https://letrasespanhol.ufam.edu.br/sobre-o-curso/ppc.html',
			c2: 'Francês',
			cl2: 'https://letrasfrances.ufam.edu.br/',
			e2: 'ppc',
			el2: 'https://drive.google.com/file/d/1ZHjCwkeEyyzJpYYVAhJnFzcSwGBjmuCD/view',
			c3: 'Português',
			cl3: 'http://www.ufopa.edu.br/iced/graduacao-1/cursos/letras/',
			e3: 'ppc',
			el3: 'https://drive.google.com/file/d/1gF3wZnrkpnqeDCX96ydClvs2vgT7gsyu/view',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 6,
		uni_nome: 'UFOPA',
		uni_link: 'https://www.ufopa.edu.br/ufopa/',
		cursos: {
			c1: 'Português',
			cl1: 'http://www.ufopa.edu.br/iced/graduacao-1/cursos/letras/',
			e1: 'e-mail',
			el1: '',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 7,
		uni_nome: 'UFT',
		uni_link: 'https://ww2.uft.edu.br/',
		cursos: {
			c1: 'Português-Inglês',
			cl1: 'https://ww2.uft.edu.br/index.php/letras-araguaina/matriz-curricular',
			e1: 'e-mail',
			el1: '',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 8,
		uni_nome: 'UFPA',
		uni_link: 'https://www.ufpa.br/',
		cursos: {
			c1: 'Letras (Por/Ing/Esp/Fra/Ale)',
			cl1: 'https://ascom.ufpa.br/index.php/cursos-da-ufpa?start=50',
			e1: 'e-mail',
			el1: '',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 9,
		uni_nome: 'UFRA',
		uni_link: 'https://novo.ufra.edu.br/',
		cursos: {
			c1: 'Português',
			cl1: 'https://letrasportugues-ta.ufra.edu.br/',
			e1: 'ppc',
			el1: 'https://letrasportugues-ta.ufra.edu.br/images/DocumentosTCC/PPC-de-Letras-2018_3_REVISO-DEFINITIVA---Agosto-2018---Novembro-2019-1.pdf',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},

	{
		id: 10,
		uni_nome: 'UNIFESSPA',
		uni_link: 'https://www.unifesspa.edu.br/',
		cursos: {
			c1: 'Português',
			cl1: 'https://crca.unifesspa.edu.br/cursos-unifesspa/30-letras-l%C3%ADngua-portuguesa-lic.html',
			e1: 'ppc',
			el1: 'https://crca.unifesspa.edu.br/images/ppc/30.4---PPCL-2015-Atualizado-via-Recomendacoes-Reparado.pdf',
			c2: '',
			cl2: '',
			e2: '',
			el2: 'https://ufrr.br/letrasfrances/wp-content/uploads/sites/32/2023/07/PPC-Letras-Frances_2018.pdf',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	}
];
