export let uni = [
	{
		id: 1,
		uni_nome: 'UnB',
		uni_link: 'http://www.unb.br/',
		cursos: {
			c1: 'Instituto de Letras',
			cl1: 'http://www.il.unb.br/',
			e1: 'ementas',
			el1: 'https://sigaa.unb.br/sigaa/public/componentes/busca_componentes.jsf',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 2,
		uni_nome: 'UFG',
		uni_link: 'https://ufg.br/',
		cursos: {
			c1: 'Português',
			cl1: 'https://letras.ufg.br/',
			e1: 'ementa',
			el1: 'https://files.cercomp.ufg.br/weby/up/508/o/Matriz_Curricular_e_Elenco_de_Disciplinas.pdf',
			c2: 'Português',
			cl2: 'https://letras.ufg.br/',
			e2: 'ppc',
			el2: 'https://files.cercomp.ufg.br/weby/up/25/o/2014_PPC_port.pdf',
			c3: 'Linguística',
			cl3: 'https://letras.ufg.br/',
			e3: 'ppc',
			el3: 'https://files.cercomp.ufg.br/weby/up/25/o/2014_PPC_ling.pdf',
			c4: 'Estudos Literários',
			cl4: 'https://letras.ufg.br/',
			e4: 'ppc',
			el4: 'https://files.cercomp.ufg.br/weby/up/25/o/2014_PPC_lit.pdfu',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 3,
		uni_nome: 'UFR',
		uni_link: 'https://ufr.edu.br/',
		cursos: {
			c1: 'Português',
			cl1: 'https://ufr.edu.br/pt-ensino-graduacao/letras-lingua-portuguesa/',
			e1: 'ementa',
			el1: 'https://ufr.edu.br/portal/wp-content/uploads/2020/01/PPC_Letras_Lingua-Portuguesa.pdf',
			c2: 'Inglês',
			cl2: 'https://ufr.edu.br/pt-ensino-graduacao/letras-lingua-inglesa/',
			e2: 'ementa',
			el2: 'https://ufr.edu.br/portal/wp-content/uploads/2020/01/PPC_Letras_Lingua-Inglesa.pdf',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 4,
		uni_nome: 'UFJ',
		uni_link: 'https://portalufj.jatai.ufg.br/',
		cursos: {
			c1: 'Letras',
			cl1: 'https://letras.jatai.ufg.br/',
			e1: 'ementa',
			el1: 'https://files.cercomp.ufg.br/weby/up/413/o/Projeto_Pedagogico_2007.pdf',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 5,
		uni_nome: 'UFGD',
		uni_link: 'https://portal.ufgd.edu.br/',
		cursos: {
			c1: 'Port-Inglês/Literatura',
			cl1: 'https://portal.ufgd.edu.br/cursos/letras/index',
			e1: 'ementa',
			el1: 'https://files.ufgd.edu.br/arquivos/arquivos/78/COGRAD/PPC%20Letras%202017.pdf',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 6,
		uni_nome: 'UFMT',
		uni_link: 'https://www.ufmt.br/',
		cursos: {
			c1: 'Letras',
			cl1: 'https://www.ufmt.br/ensino/busca?text=&modality=PRESENCIAL&type=&campus=&period=',
			e1: 'ementa',
			el1: 'https://cms.ufmt.br/files/galleries/160/Pad49816d9adef50439e096ec25ed3c27b171dc4c.pdf',
			c2: '',
			cl2: '',
			e2: '',
			el2: '',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 7,
		uni_nome: 'UFCAT',
		uni_link: 'https://portal.ufcat.edu.br/',
		cursos: {
			c1: 'Português',
			cl1: 'https://letras.catalao.ufg.br/',
			e1: 'ppc',
			el1: 'https://files.cercomp.ufg.br/weby/up/508/o/Resolucao_CEPEC_2019_1634.pdf',
			c2: 'Inglês',
			cl2: 'https://letras.catalao.ufg.br/',
			e2: 'ppc',
			el2: 'https://files.cercomp.ufg.br/weby/up/508/o/PPC_Portugu%C3%AAs_e_Ingl%C3%AAs.pdf',
			c3: '',
			cl3: '',
			e3: '',
			el3: '',
			c4: '',
			cl4: '',
			e4: '',
			el4: '',
			c5: '',
			cl5: '',
			e5: '',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	},
	{
		id: 8,
		uni_nome: 'UFMS',
		uni_link: 'https://graduacao.ufms.br/',
		cursos: {
			c1: 'Letras',
			cl1: 'https://graduacao.ufms.br/cursos/0432',
			e1: 'e-mail',
			el1: '',
			c2: 'Português/Espanhol',
			cl2: 'https://graduacao.ufms.br/cursos/2908',
			e2: 'e-mail',
			el2: '',
			c3: 'Português/Inglês',
			cl3: 'https://graduacao.ufms.br/cursos/2909',
			e3: 'e-mail',
			el3: '',
			c4: 'Português e Espanhol',
			cl4: 'https://graduacao.ufms.br/cursos/2912',
			e4: 'e-mail',
			el4: '',
			c5: 'Português e Inglês',
			cl5: 'https://graduacao.ufms.br/cursos/2913',
			e5: 'e-mail',
			el5: '',
			c6: '',
			cl6: '',
			e6: '',
			el6: '',
			c7: '',
			cl7: '',
			e7: '',
			el7: ''
		}
	}
];
